version: "3"

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - python-api
      - db
    env_file:
      - .env.docker

  python-api:
    build:
      context: ./python
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_DATABASE=${PG_DATABASE}
    volumes:
      - ./python:/app
      - ./uploads:/app/uploads
      - python_temp:/app/temp_uploads
    depends_on:
      - db
    env_file:
      - .env.docker

  db:
    image: postgres:14
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.docker

volumes:
  postgres_data:
  python_temp:
